# Generated by Django 3.2.6 on 2021-08-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(verbose_name='release date'),
        ),
    ]
