# Generated by Django 3.2.6 on 2021-08-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_length',
        ),
    ]
